// <auto-generated />
using System;
using Cyrella;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cyrella.Migrations
{
    [DbContext(typeof(CyrellaDbContext))]
    partial class CyrellaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Cyrella.Model.AgendamentoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaDeAssistencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comodo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoDefeito")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtAberturaChamado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemComDefeito")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recorrencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AgendamentoManutencao");
                });

            modelBuilder.Entity("Cyrella.Model.ImagemAgendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgendamentoManutencaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoManutencaoId");

                    b.ToTable("ImagensAgendamentos");
                });

            modelBuilder.Entity("Cyrella.Model.ImagemAgendamento", b =>
                {
                    b.HasOne("Cyrella.Model.AgendamentoManutencao", null)
                        .WithMany("ImagensAnexas")
                        .HasForeignKey("AgendamentoManutencaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
